# Generated by Django 4.2.23 on 2025-09-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('news', 'News Media'), ('social', 'Social Media')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('author_username', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField()),
                ('likes_count', models.IntegerField(default=0)),
                ('retweets_count', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(blank=True, to='scraper.keyword')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.source')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(blank=True, to='scraper.keyword')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.source')),
            ],
        ),
    ]
